B3_NguyenMinhThuan_2011061100/ViewModels/CoursesViewModel.cs
using B3_NguyenMinhThuan_2011061100.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace B3_NguyenMinhThuan_2011061100.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<Course> UpcommingCourses { get; set; }
        public bool ShowAction { get; set; }
    }
}

B3_NguyenMinhThuan_2011061100/Controllers/CoursesController.cs
using B3_NguyenMinhThuan_2011061100.Models;
using B3_NguyenMinhThuan_2011061100.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security.Provider;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B3_NguyenMinhThuan_2011061100.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbcontext;
        public CoursesController()
        {
            _dbcontext = new ApplicationDbContext();
        }
        // GET: Courses
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbcontext.Categories.ToList()
            };
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbcontext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place
            };
            _dbcontext.Courses.Add(course);
            _dbcontext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();

            var courses =_dbcontext.Attendances
                .Where(a  => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(l => l.Lecturer)
                .Include(l => l.Category)
                .ToList();
            var viewModel = new CoursesViewModel
            {
                UpcommingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewModel);
        }

    }
}

B3_NguyenMinhThuan_2011061100/Views/Courses/Attending.cshtml
@model B3_NguyenMinhThuan_2011061100.ViewModels.CoursesViewModel
@{
    ViewBag.Title = "Home Page";
}
<ul class="course">
    @foreach (var course in Model.UpcommingCourses)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                    @if (Model.ShowAction)
                    {
                        <button class="btn btn-default btn-sm js-toggle-follow" data--user-id="@course.Lecturer">
                            Follow
                        </button>
                    }
                </span>
                <span class="category">
                    @course.Category.Name
                </span>
                @if (Model.ShowAction)
                {
                    <button data-course-id="@course.Id" class="btn btn-default btn-sm js-toggle-attendance">Going?</button>
                }
            </div>
        </li>

    }
</ul>
@section scripts
{
    <script>
        $(document).ready(function(){
            $(".js-toggle-attendance").click(function (e){
                var button = $(e.target);
                $.post("/api/attendances", { courseId: button.attr("data-course-id") })
                    .done(function () {
                        button
                            .removeClass("btn-default")
                            .addClass("btn-info")
                            .text("Going");
                    })
                    .fail(function () {
                        alert("Something failed !");
                    });
            });
        $(".js-toggle-follow").click(function (e){
            var button = $(e.target);
            $.post("/api/followings", { followeeId:button.attr("date-user-id") })
                .done(function () {
                    button.text("Following");
                })
                .fail(function () {
                    alert("Something failed !");
                });
        });
});
    </script>
}

B3_NguyenMinhThuan_2011061100/Views/Courses/Create.cshtml
@model B3_NguyenMinhThuan_2011061100.ViewModels.CourseViewModel
    @{ 
        ViewBag.Title = "Create";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
@using (Html.BeginForm("Create", "Courses"))

{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Place)
        @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Place)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
           @Html.ValidationMessageFor(m=> m.Date)
    </div>

    <div class="form-group">
         @Html.LabelFor(m => m.Time)
         @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
         @Html.ValidationMessageFor(m=> m.Time)
         </div>
    <div class="form-group">
         @Html.LabelFor(m => m.Category)
         @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = " form-control"})
        @Html.ValidationMessageFor(m=> m.Category)
    </div>
<button type="submit" value="Save" class="btn btn-primary">Save</button>
}